'use client';
import {useState,useEffect,useRef} from 'react';
import {Heart,Plus,Upload,GripVertical,Eye,EyeOff,Pencil,Trash2,ArrowUp,ArrowDown,ImageIcon,Film,Type,Music2,ArrowUpRight,Check,Save} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {type Content,type Memory,type Moment,type Reason,type Settings,defaults} from '@/lib/content';
import {uploadMedia,upload,fileType,mediaAccept} from '@/lib/upload';
type Entity='memories'|'timeline'|'reasons'|'settings';
type Edit={entity:'memories';item:Memory}|{entity:'timeline';item:Moment}|{entity:'reasons';item:Reason};
async function api(body:unknown){const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as {ok?:boolean;error?:string};if(!r.ok)throw new Error(j.error);return j;}
export default function Admin(){
 const [data,setData]=useState<Content|null>(null),[settings,setSettings]=useState<Settings>(defaults),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[uploadLabel,setUploadLabel]=useState(''),[choosing,setChoosing]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[deleting,setDeleting]=useState<{entity:Entity;id:string}|null>(null),[dragging,setDragging]=useState(''),[over,setOver]=useState(false),[dirty,setDirty]=useState(false);
 const files=useRef<HTMLInputElement>(null);const queuedType=useRef('');const reorderStart=useRef<string|null>(null);
 async function load(reset=false){const r=await fetch('/api/content?preview=1',{cache:'no-store'});const j=await r.json() as Content & {error?:string};if(!r.ok)throw new Error(j.error);setData(j);if(reset)setSettings(j.settings);return j;}
 useEffect(()=>{load(true).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,busy]);
 async function run(fn:()=>Promise<void>,message='Cambios guardados'){setBusy(true);setError('');try{await fn();await load();toast.success(message);}catch(e){setError((e as Error).message);toast.error((e as Error).message);}finally{setBusy(false);}}
 function change<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(s=>({...s,[key]:value}));setDirty(true);}
 function newMemory(type:Memory['type']){setChoosing(false);setEdit({entity:'memories',item:{id:crypto.randomUUID(),type,media_url:'',thumbnail_url:'',title:type==='gif'?'Chiikawa también vino a desearte feliz cumpleaños 🎂':'',description:'',date:'',sort_order:data?.memories.length||0,visible:1,style:'paper',size:'medium'}});}
 async function bulk(input:FileList|File[]|null){if(!input||busy)return;const list=Array.from(input);if(!list.length)return;setBusy(true);setError('');setProgress(0);let saved=0;const failures:string[]=[];let latest:Memory|null=null;for(let i=0;i<list.length;i++){const file=list[i];setUploadLabel(`Subiendo ${i+1} de ${list.length}: ${file.name}`);try{const media=await uploadMedia(file,n=>setProgress(Math.round((i+n/100)/list.length*100)));latest={id:crypto.randomUUID(),...media,title:'',description:'',date:'',sort_order:(data?.memories.length||0)+saved,visible:1,style:'paper',size:'medium'};await api({action:'save',entity:'memories',data:latest});saved++;}catch(e){failures.push(file.name+': '+(e as Error).message);}}try{await load();}catch(e){failures.push((e as Error).message);}setBusy(false);setUploadLabel('');setProgress(100);if(saved)toast.success(`${saved} recuerdo${saved===1?'':'s'} guardado${saved===1?'':'s'}`);if(failures.length)setError(failures.join('\n'));else if(list.length===1&&latest)setEdit({entity:'memories',item:latest});if(files.current)files.current.value='';}
 async function reorder(entity:'memories'|'timeline'|'reasons',from:string,to:string){if(!data||from===to||busy)return;const items=[...data[entity]];const start=items.findIndex(x=>x.id===from),end=items.findIndex(x=>x.id===to);if(start<0||end<0)return;const [item]=items.splice(start,1);items.splice(end,0,item);await run(async()=>{await api({action:'reorder',entity,ids:items.map(x=>x.id)});},'Orden actualizado');}
 function arrows(entity:'memories'|'timeline'|'reasons',id:string,i:number){const items=data![entity];return <><button disabled={busy||i===0} className="icon-button" aria-label="Mover antes" onClick={()=>void reorder(entity,id,items[i-1].id)}><ArrowUp size={16}/></button><button disabled={busy||i===items.length-1} className="icon-button" aria-label="Mover después" onClick={()=>void reorder(entity,id,items[i+1].id)}><ArrowDown size={16}/></button></>;}
 async function saveSettings(keys:(keyof Settings)[]){await run(async()=>{await api({action:'save',entity:'settings',data:Object.fromEntries(keys.map(k=>[k,settings[k]]))});setDirty(false);});}
 async function uploadSetting(file:File|undefined,key:'audio_url'|'cover_url'){if(!file)return;setBusy(true);setUploadLabel('Subiendo '+file.name);try{let url='';if(key==='cover_url'){const result=await uploadMedia(file,setProgress);if(result.type==='video')throw new Error('Elige una imagen de portada.');url=result.media_url;}else{if(file.size>95*1024*1024)throw new Error('La canción supera los 95 MB.');url=await upload(new Blob([file],{type:fileType(file)}),setProgress);}change(key,url);toast.success('Archivo subido. Guarda los cambios para publicarlo.');}catch(e){setError((e as Error).message);}finally{setBusy(false);setUploadLabel('');}}
 if(!data)return <main className="access-page"><p className="eyebrow">PREPARANDO NUESTRA SORPRESA</p><h1>Un momento…</h1>{error&&<div role="alert"><p>{error}</p><button className="primary" onClick={()=>load(true).catch(e=>setError(e.message))}>Reintentar</button></div>}</main>;
 return <main className="admin"><Toaster richColors position="bottom-center"/><header className="admin-header"><a href="/" className="brand"><Heart size={22} strokeWidth={1}/> Nuestro rincón</a><div><a className="outline-button" href="/admin/preview" target="_blank" rel="noopener">Previsualizar <ArrowUpRight size={16}/></a><a className="text-button" href="/signout-with-chatgpt?return_to=/">Cerrar sesión</a></div></header><div className="admin-intro"><p className="eyebrow">DETRÁS DE LA SORPRESA</p><h1>Cada detalle, <em>para ella.</em></h1><p>Aquí se guardan las cosas que hacen nuestro rincón único.</p></div>
 {error&&<div className="admin-error" role="alert">{error}<button aria-label="Cerrar aviso" onClick={()=>setError('')}>×</button></div>}
 {uploadLabel&&<div className="upload-progress" aria-live="polite"><p>{uploadLabel}</p><Progress value={progress}/><small>{progress}%</small></div>}
 <Tabs defaultValue="memories" className="admin-tabs"><TabsList className="admin-nav" variant="line">{[['memories','Recuerdos'],['letter','Carta'],['timeline','Nuestra historia'],['reasons','Frases'],['music','Música'],['settings','Configuración']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList>
 <TabsContent value="memories"><div className="admin-section-head"><div><h2>Nuestros recuerdos</h2><p>{data.memories.length} recuerdos · Arrastra las tarjetas para cambiar el orden.</p></div><button className="primary" disabled={busy} onClick={()=>setChoosing(true)}><Plus size={17}/> Agregar recuerdo</button></div>
 <input ref={files} type="file" className="sr-only" multiple accept={mediaAccept} onChange={e=>void bulk(e.target.files)} aria-label="Subir recuerdos"/>
 <button disabled={busy} className={'dropzone '+(over?'drag-over':'')} onClick={()=>files.current?.click()} onDragOver={e=>{e.preventDefault();setOver(true);}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);void bulk(e.dataTransfer.files);}}><Upload size={26} strokeWidth={1.3}/><strong>Arrastra nuestros recuerdos aquí ❤️</strong><span>O elige varios archivos · Fotos, videos y GIF · Hasta 95 MB por archivo</span></button>
 {!data.memories.length?<div className="admin-empty"><Heart size={28} strokeWidth={1}/><h3>Todo empieza con un recuerdo.</h3><p>Sube sus fotos, un video o ese GIF que siempre los hace sonreír.</p></div>:<div className="admin-grid">{data.memories.map((m,i)=><article key={m.id} className={'admin-memory '+(!m.visible?'is-hidden':'')+(dragging===m.id?' is-dragging':'')} draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',m.id);setDragging(m.id);reorderStart.current=m.id;}} onDragEnd={()=>{setDragging('');reorderStart.current=null;}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=reorderStart.current||e.dataTransfer.getData('text/plain');setDragging('');void reorder('memories',from,m.id);}}><div className="admin-thumb" onDoubleClick={()=>setEdit({entity:'memories',item:m})}>{m.type==='text'?<blockquote>{m.title||m.description}</blockquote>:m.type==='video'&&!m.thumbnail_url?<Film size={35}/>:<img loading="lazy" src={m.thumbnail_url||m.media_url} alt={m.title||'Recuerdo'}/>}<span className="media-badge">{m.type==='photo'?'FOTO':m.type==='video'?'VIDEO':m.type==='gif'?'GIF':'TEXTO'}</span><GripVertical className="drag-grip" size={20}/></div><div className="admin-memory-body"><h3>{m.title||'Un recuerdo sin título'}</h3><p>{m.description||'Agrega unas palabras para este momento.'}</p><div className="card-actions">{arrows('memories',m.id,i)}<button disabled={busy} className="icon-button" aria-label={m.visible?'Ocultar recuerdo':'Mostrar recuerdo'} onClick={()=>void run(async()=>{await api({action:'save',entity:'memories',data:{...m,visible:m.visible?0:1}});})}>{m.visible?<Eye size={16}/>:<EyeOff size={16}/>}</button><button disabled={busy} className="icon-button" aria-label="Editar recuerdo" onClick={()=>setEdit({entity:'memories',item:m})}><Pencil size={16}/></button><button disabled={busy} className="icon-button danger" aria-label="Eliminar recuerdo" onClick={()=>setDeleting({entity:'memories',id:m.id})}><Trash2 size={16}/></button></div></div></article>)}</div>}</TabsContent>
 <TabsContent value="letter"><div className="admin-section-head"><div><h2>Una carta para ti</h2><p>Tus propias palabras. Todos los párrafos que necesites.</p></div></div><div className="admin-form narrow"><label htmlFor="letter">La carta</label><textarea id="letter" className="letter-editor" rows={15} maxLength={50000} value={settings.letter_content} onChange={e=>change('letter_content',e.target.value)}/><button className="primary" disabled={busy} onClick={()=>void saveSettings(['letter_content'])}><Save size={16}/> Guardar carta</button></div></TabsContent>
 <TabsContent value="timeline"><div className="admin-section-head"><div><h2>Nuestra historia</h2><p>Esos momentos que merecen una página propia.</p></div><button className="primary" disabled={busy} onClick={()=>setEdit({entity:'timeline',item:{id:crypto.randomUUID(),date:'',title:'',description:'',media_url:'',sort_order:data.timeline.length}})}><Plus size={17}/> Agregar momento</button></div><div className="switch-row"><Switch id="timeline-on" checked={settings.timeline_enabled} onCheckedChange={v=>change('timeline_enabled',v)}/><label htmlFor="timeline-on">Mostrar nuestra historia</label><button className="text-button" disabled={busy} onClick={()=>void saveSettings(['timeline_enabled'])}>Guardar</button></div><div className="editor-list">{data.timeline.map((t,i)=><article key={t.id}>{t.media_url&&<img src={t.media_url} alt={t.title} loading="lazy"/>}<div><small>{t.date||'Sin fecha'}</small><h3>{t.title}</h3><p>{t.description}</p></div><div className="card-actions">{arrows('timeline',t.id,i)}<button className="icon-button" disabled={busy} aria-label="Editar momento" onClick={()=>setEdit({entity:'timeline',item:t})}><Pencil size={16}/></button><button className="icon-button danger" disabled={busy} aria-label="Eliminar momento" onClick={()=>setDeleting({entity:'timeline',id:t.id})}><Trash2 size={16}/></button></div></article>)}</div>{!data.timeline.length&&<p className="admin-empty">Agrega su primer encuentro, una salida, un viaje…</p>}</TabsContent>
 <TabsContent value="reasons"><div className="admin-section-head"><div><h2>Pequeñas cosas que amo de ti</h2><p>Una sonrisa, una ocurrencia, su forma de mirar.</p></div><button className="primary" disabled={busy} onClick={()=>setEdit({entity:'reasons',item:{id:crypto.randomUUID(),text:'',sort_order:data.reasons.length}})}><Plus size={17}/> Agregar frase</button></div><div className="editor-list">{data.reasons.map((r,i)=><article key={r.id}><span className="reason-number">{String(i+1).padStart(2,'0')}</span><h3>{r.text}</h3><div className="card-actions">{arrows('reasons',r.id,i)}<button className="icon-button" disabled={busy} aria-label="Editar frase" onClick={()=>setEdit({entity:'reasons',item:r})}><Pencil size={16}/></button><button className="icon-button danger" disabled={busy} aria-label="Eliminar frase" onClick={()=>setDeleting({entity:'reasons',id:r.id})}><Trash2 size={16}/></button></div></article>)}</div></TabsContent>
 <TabsContent value="music"><div className="admin-section-head"><div><h2>Nuestra canción</h2><p>Sonará solo cuando ella toque el reproductor.</p></div></div><div className="admin-form narrow"><label>Subir canción<input disabled={busy} type="file" accept=".mp3,.m4a,.wav,.ogg,.aac" onChange={e=>void uploadSetting(e.target.files?.[0],'audio_url')}/></label><label>O pegar una URL de audio<input value={settings.audio_url} placeholder="https://…/nuestra-cancion.mp3" onChange={e=>change('audio_url',e.target.value)}/></label>{settings.audio_url&&<audio key={settings.audio_url} src={settings.audio_url} controls preload="none"/>}<div className="form-actions"><button className="primary" disabled={busy} onClick={()=>void saveSettings(['audio_url'])}><Save size={16}/> Guardar música</button><button className="text-button" disabled={busy} onClick={()=>change('audio_url','')}>Quitar canción</button></div></div></TabsContent>
 <TabsContent value="settings"><div className="admin-section-head"><div><h2>Los pequeños detalles</h2><p>La portada, las primeras palabras y el momento de abrir la sorpresa.</p></div></div><div className="admin-form narrow"><label>Mensaje principal<input value={settings.main_message} maxLength={300} onChange={e=>change('main_message',e.target.value)}/></label><label>Texto de bienvenida<textarea rows={3} value={settings.intro} maxLength={1000} onChange={e=>change('intro',e.target.value)}/></label><label>Fecha y hora · Lima, Perú (UTC−05:00)<input type="datetime-local" value={settings.birthday_date.slice(0,16)} onChange={e=>change('birthday_date',e.target.value+':00-05:00')}/></label><label>Cambiar portada<input disabled={busy} type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>void uploadSetting(e.target.files?.[0],'cover_url')}/></label>{settings.cover_url&&<img className="cover-preview" src={settings.cover_url} alt="Portada actual"/>}<button type="button" className="text-button" onClick={()=>change('cover_url','/romantic-rose-letter.webp')}>Usar la portada de la rosa</button><button className="primary" disabled={busy} onClick={()=>void saveSettings(['main_message','intro','birthday_date','cover_url'])}><Save size={16}/> Guardar configuración</button></div></TabsContent></Tabs>
 <Dialog open={choosing} onOpenChange={setChoosing}><DialogContent className="admin-dialog"><DialogTitle>Un nuevo recuerdo</DialogTitle><DialogDescription>Elige qué quieres guardar en nuestro rincón.</DialogDescription><div className="type-choices">{([['photo','Foto',ImageIcon],['video','Video',Film],['gif','GIF',Heart],['text','Texto',Type]] as const).map(([type,label,Icon])=><button key={type} onClick={()=>newMemory(type)}><Icon size={26} strokeWidth={1.3}/>{label}</button>)}</div></DialogContent></Dialog>
 {edit&&<Editor key={edit.item.id} edit={edit} onClose={()=>setEdit(null)} onSave={async value=>{await api({action:'save',entity:edit.entity,data:value});await load();setEdit(null);toast.success('Recuerdo guardado');}}/>}
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent><AlertDialogTitle>¿Eliminar este recuerdo?</AlertDialogTitle><AlertDialogDescription>Se quitará del sitio. Para retirarlo temporalmente, puedes ocultarlo desde el icono del ojo.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Conservar</AlertDialogCancel><AlertDialogAction onClick={()=>{const d=deleting;setDeleting(null);if(d)void run(async()=>{await api({action:'delete',...d});},'Elemento eliminado');}}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
function Editor({edit,onClose,onSave}:{edit:Edit;onClose:()=>void;onSave:(value:Memory|Moment|Reason)=>Promise<void>}){
 const [item,setItem]=useState<Memory|Moment|Reason>(edit.item),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
 const m=item as Memory;const isMemory=edit.entity==='memories',isReason=edit.entity==='reasons';
 function change(key:string,value:unknown){setItem(v=>({...v,[key]:value}));}
 async function file(f:File|undefined,poster=false){if(!f)return;setBusy(true);setError('');try{const result=await uploadMedia(f,setProgress);if(poster){if(result.type!=='photo')throw new Error('La miniatura debe ser una imagen.');change('thumbnail_url',result.media_url);}else if(isMemory){if(result.type!==m.type)throw new Error('El archivo no corresponde al tipo de recuerdo seleccionado.');setItem(v=>({...v,...result}));}else{if(result.type!=='photo')throw new Error('Elige una fotografía para este momento.');change('media_url',result.media_url);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await onSave(item);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="admin-dialog editor-dialog"><DialogTitle>{isReason?'Una cosa que amo de ti':isMemory?'Editar recuerdo':'Un momento de nuestra historia'}</DialogTitle><DialogDescription>{isReason?'Una frase corta, escrita con amor.':'Los títulos, las fechas y los mensajes acompañarán este recuerdo.'}</DialogDescription><div className="admin-form">
 {isReason?<label>Frase<input autoFocus maxLength={300} value={(item as Reason).text} onChange={e=>change('text',e.target.value)}/></label>:<>
 {(!isMemory||m.type!=='text')&&<><label>{m.media_url?'Cambiar archivo':'Elegir archivo'}<input disabled={busy} type="file" accept={!isMemory||m.type==='photo'?'.jpg,.jpeg,.png,.webp':m.type==='video'?'.mp4,.mov,.webm':'.gif'} onChange={e=>void file(e.target.files?.[0])}/></label>{isMemory&&m.type==='gif'&&<label>O pegar URL directa del GIF<input value={m.media_url} placeholder="https://…" onChange={e=>change('media_url',e.target.value)}/></label>}{m.media_url&&(m.type==='video'?<video className="edit-preview" src={m.media_url} controls preload="none" poster={m.thumbnail_url||undefined}/>:<img className="edit-preview" src={m.media_url} alt="Vista previa del recuerdo"/>)}{isMemory&&m.type==='video'&&<label>Miniatura del video (opcional)<input disabled={busy} type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>void file(e.target.files?.[0],true)}/></label>}</>}
 <label>{isMemory&&m.type==='text'?'Frase':'Título'}<input maxLength={180} value={m.title} onChange={e=>change('title',e.target.value)}/></label><label>Mensaje<textarea rows={3} maxLength={4000} value={m.description} onChange={e=>change('description',e.target.value)}/></label><label>Fecha (opcional)<input type="date" value={m.date} onChange={e=>change('date',e.target.value)}/></label>
 {isMemory&&m.type==='text'&&<div className="form-row"><label>Estilo<Select value={m.style} onValueChange={v=>change('style',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="paper">Papel champagne</SelectItem><SelectItem value="wine">Vino profundo</SelectItem></SelectContent></Select></label><label>Tamaño<Select value={m.size} onValueChange={v=>change('size',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="small">Pequeño</SelectItem><SelectItem value="medium">Mediano</SelectItem><SelectItem value="large">Grande</SelectItem></SelectContent></Select></label></div>}
 {isMemory&&<div className="switch-row"><Switch id="visible-memory" checked={!!m.visible} onCheckedChange={v=>change('visible',v?1:0)}/><label htmlFor="visible-memory">Visible en el álbum</label></div>}</>}
 {busy&&<Progress value={progress}/>} {error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy} onClick={()=>void save()}><Check size={16}/>{busy?'Guardando…':'Guardar recuerdo'}</button><button className="text-button" disabled={busy} onClick={onClose}>Cancelar</button></div></div></DialogContent></Dialog>;
}
