'use client';
import {useState,useEffect,useRef} from 'react';
import {Heart,ArrowDown,ChevronLeft,ChevronRight,Play,Pause,RotateCcw,Volume2,Music2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Slider} from '@/components/ui/slider';
import {type Content,type Memory,limaDate} from '@/lib/content';
export default function Album({data,preview}:{data:Content;preview:boolean}){
 const {settings,memories,timeline,reasons}=data;const [selected,setSelected]=useState<string|null>(null),[letter,setLetter]=useState(false),[surprise,setSurprise]=useState(false),[greeting,setGreeting]=useState(false),[secret,setSecret]=useState(false),[hearts,setHearts]=useState(0),[loved,setLoved]=useState<string[]>([]);
 const media=memories.filter(m=>m.type!=='text');const index=media.findIndex(m=>m.id===selected);const current=media[index];const touch=useRef(0);
 function move(n:number){if(media.length)setSelected(media[(index+n+media.length)%media.length].id);}
 useEffect(()=>{if(!selected)return;function key(e:KeyboardEvent){if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected,media.length]);
 function heart(){setHearts(v=>v+1);if((hearts+1)%5===0)setSecret(true);}
 const cut=Math.ceil(memories.length*.5);const lastCut=Math.ceil(memories.length*.85);
 function collage(items:Memory[]){return <div className="collage">{items.map(m=><article key={m.id} className={'memory reveal '+(m.type==='text'?'text-memory '+m.style+' '+m.size:m.type==='gif'?'gif-memory':'')}><button onClick={()=>m.type==='text'?setLoved(v=>v.includes(m.id)?v.filter(x=>x!==m.id):[...v,m.id]):setSelected(m.id)} aria-label={m.type==='text'?m.title||m.description:'Abrir '+(m.title||'recuerdo')}>{m.type==='text'?<Heart className="heart-outline" size={24} strokeWidth={1} fill={loved.includes(m.id)?'currentColor':'none'}/>:<div className="media-wrap">{m.type==='video'?(m.thumbnail_url?<img loading="lazy" decoding="async" src={m.thumbnail_url} alt={m.title||'Video de nuestro recuerdo'}/>:<div className="video-poster"><Music2 size={28}/></div>):<img loading="lazy" decoding="async" src={m.type==='gif'?m.media_url:m.thumbnail_url||m.media_url} alt={m.title||'Un recuerdo juntos'}/>} {m.type==='video'&&<span className="play-overlay"><Play fill="currentColor"/></span>}</div>}{m.title&&<h3>{m.title}</h3>}{m.description&&<p>{m.description}</p>}{m.date&&<time>{new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'}).format(new Date(m.date+'T12:00:00-05:00'))}</time>}</button></article>)}</div>;}
 return <main className="album">{preview&&<div className="preview-banner">Vista previa privada <a href="/admin">Volver al panel</a></div>}
 <header className="album-header"><button className="brand" onClick={()=>setGreeting(true)}><Heart size={18} strokeWidth={1}/> Para mi preciosita</button><nav><a href="#recuerdos">Recuerdos</a><a href="#carta">La carta</a><a href="#amor">Para ti</a></nav></header>
 <section className="album-hero"><p className="eyebrow">{limaDate(settings.birthday_date)} · UN DÍA PARA CELEBRARTE</p><h1>La vida es más bonita<br/><em>contigo.</em></h1><p>Hay instantes que duran un segundo.<br/>Y recuerdos que se quedan para siempre.</p><p className="main-message">{settings.main_message}</p><a className="scroll-note" href="#recuerdos">Un pedacito de nosotros <ArrowDown size={15}/></a></section>
 <section id="recuerdos" className="section"><div className="chapter"><span>01</span><p>Los días que guardo en el corazón</p></div>{memories.length?collage(memories.slice(0,cut)):<div className="empty-album"><img src={settings.cover_url||'/romantic-rose-letter.webp'} alt="Una rosa y una carta, con todo mi amor"/><div><blockquote>Contigo, cualquier lugar<br/>se vuelve <em>especial.</em></blockquote><p>Este es nuestro rincón.<br/>Y todo lo bonito que todavía nos falta vivir.</p></div></div>}</section>
 <section className="pause"><Heart size={30} strokeWidth={1}/><blockquote>De todos los lugares<br/>en los que podría estar,<br/>mi favorito siempre será <em>contigo.</em></blockquote><p>Feliz cumpleaños, preciosita de mi corazón ❤️</p></section>
 {memories.length>cut&&<section className="section">{collage(memories.slice(cut,lastCut))}</section>}
 {settings.timeline_enabled&&timeline.length>0&&<section className="section" id="historia"><div className="chapter"><span>02</span><p>El principio de tantas cosas bonitas</p></div><h2 className="section-heading">Nuestra <em>historia.</em></h2><div className="timeline">{timeline.map(t=><article key={t.id} className="reveal"><time>{t.date&&new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'}).format(new Date(t.date+'T12:00:00-05:00'))}</time><h3>{t.title}</h3>{t.media_url&&<img src={t.media_url} loading="lazy" alt={t.title}/>}<p>{t.description}</p></article>)}</div><p className="timeline-end">Y todo lo que todavía nos falta vivir…</p></section>}
 {reasons.length>0&&<section className="section" id="amor"><div className="chapter"><span>03</span><p>Podría seguir para siempre</p></div><h2 className="section-heading">Pequeñas cosas<br/>que <em>amo de ti.</em></h2><div className="reasons">{reasons.map((r,i)=><button key={r.id} className={'reason '+(loved.includes(r.id)?'loved':'')} onClick={()=>setLoved(v=>v.includes(r.id)?v.filter(x=>x!==r.id):[...v,r.id])} aria-pressed={loved.includes(r.id)}><small>{String(i+1).padStart(2,'0')}</small><span>{r.text}</span></button>)}</div></section>}
 <section className="section letter-section" id="carta"><div className="chapter"><span>04</span><p>Hay cosas que quiero decirte</p></div><h2 className="section-heading">Una carta <em>para ti.</em> 💌</h2><div className="envelope"><div className="wax"><Heart size={28} strokeWidth={1}/></div><h3>Solo tú y estas palabras.</h3><p className="eyebrow">PARA MI PERSONA FAVORITA</p><button className="text-button" aria-expanded={letter} aria-controls="letter-paper" onClick={()=>setLetter(v=>!v)}>{letter?'Guardar la carta':'Abrir carta'} <span aria-hidden="true">↗</span></button></div>{letter&&<article id="letter-paper" className="letter-paper"><p>{settings.letter_content}</p><span className="signature">Siempre, contigo. ♡</span></article>}</section>
 <section className="surprise"><button className="primary" onClick={()=>setSurprise(true)}>Tengo otra cosita para ti <Heart size={17}/></button></section>
 {memories.length>lastCut&&<section className="section">{collage(memories.slice(lastCut))}</section>}
 <footer className="finale"><p>Y todavía nos faltan muchísimos recuerdos por agregar aquí…</p><h2>Feliz cumpleaños,<br/><em>preciosita de mi corazón.</em> ❤️</h2><p className="love">Te amo.</p><button onClick={heart} aria-label="Un corazón para ti"><Heart className="heartbeat" size={27} strokeWidth={1}/></button><small>{limaDate(settings.birthday_date)}</small><p className="ps">GRACIAS POR ESTAR EN MI VIDA</p></footer>
 {settings.audio_url&&<Player url={settings.audio_url}/>}
 <Dialog open={!!current} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="lightbox"><DialogTitle className="sr-only">{current?.title||'Nuestro recuerdo'}</DialogTitle><DialogDescription className="sr-only">Usa las flechas o desliza para recorrer nuestros recuerdos.</DialogDescription>{current&&<><div className="lightbox-media" onTouchStart={e=>{touch.current=e.changedTouches[0].clientX;}} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>60)move(d>0?-1:1);}}>{current.type==='video'?<video key={current.id} src={current.media_url} poster={current.thumbnail_url||undefined} controls playsInline autoPlay preload="metadata" onPlay={()=>window.dispatchEvent(new Event('memory-video-play'))}/>:<img key={current.id} src={current.media_url} alt={current.title||'Nuestro recuerdo'}/>}</div><div className="lightbox-caption"><h2>{current.title}</h2><p>{current.description}</p></div><div className="lightbox-nav"><button aria-label="Recuerdo anterior" onClick={()=>move(-1)}><ChevronLeft size={21}/></button><span>{index+1} / {media.length}</span><button aria-label="Recuerdo siguiente" onClick={()=>move(1)}><ChevronRight size={21}/></button></div></>}</DialogContent></Dialog>
 <Dialog open={surprise||greeting||secret} onOpenChange={v=>{if(!v){setSurprise(false);setGreeting(false);setSecret(false);}}}><DialogContent className="romantic-dialog"><div className="mini-hearts" aria-hidden="true">♡ ♡ ♡</div><DialogTitle>{greeting?settings.main_message:secret?'¿Encontraste el secreto?':'Por si todavía no quedó suficientemente claro…'}</DialogTitle>{!greeting&&<div className="love-big">TE AMO ❤️</div>}<DialogDescription>{secret?'Pues sí… te amo muchísimo ❤️':greeting?'Hoy, y todos los días, celebro tenerte en mi vida.':'Y espero poder celebrar muchísimos cumpleaños más contigo.'}</DialogDescription></DialogContent></Dialog>
 </main>;
}
function Player({url}:{url:string}){
 const ref=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false),[expanded,setExpanded]=useState(false),[volume,setVolume]=useState(.6),[error,setError]=useState('');
 useEffect(()=>{const pause=()=>ref.current?.pause();window.addEventListener('memory-video-play',pause);return()=>window.removeEventListener('memory-video-play',pause);},[]);
 async function toggle(){setExpanded(true);if(!ref.current)return;if(playing)ref.current.pause();else{ref.current.volume=volume;try{await ref.current.play();setError('');}catch{setError('No pudimos reproducir la canción. Inténtalo otra vez.');}}}
 return <div className="music"><audio ref={ref} src={url} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>setError('La canción no está disponible.')}/><button className="music-toggle" onClick={toggle}>{playing?<Pause size={15}/>:<Play size={15}/>} Nuestra canción <Music2 size={14}/></button>{expanded&&<div className="music-controls"><button aria-label="Reiniciar canción" onClick={()=>{if(ref.current)ref.current.currentTime=0;}}><RotateCcw size={15}/></button><Volume2 size={15}/><Slider aria-label="Volumen de la canción" value={[volume]} min={0} max={1} step={.05} onValueChange={v=>{setVolume(v[0]);if(ref.current)ref.current.volume=v[0];}}/><button aria-label="Ocultar controles" onClick={()=>setExpanded(false)}>−</button></div>}{error&&<p className="music-error" role="alert">{error}</p>}</div>;
}
