'use client';
import {useState,useEffect,useRef,lazy,Suspense} from 'react';
import {Heart,ArrowRight} from 'lucide-react';
import {defaults,remaining,limaDate,type Content} from '@/lib/content';
const Album=lazy(()=>import('./album'));
export default function Experience({preview=false}:{preview?:boolean}){
 const [data,setData]=useState<Content|null>(null),[error,setError]=useState(''),[now,setNow]=useState(0),[entered,setEntered]=useState(false),[leaving,setLeaving]=useState(false);
 const clock=useRef({server:0,at:0});const refresh=useRef<()=>Promise<void>>(async()=>{});const reaching=useRef(false);
 useEffect(()=>{let alive=true;async function load(){try{const start=performance.now();const r=await fetch('/api/content'+(preview?'?preview=1':''),{cache:'no-store'});const j=await r.json() as Content & {error?:string};if(!r.ok)throw new Error(j.error);if(!alive)return;clock.current={server:j.serverTime+(performance.now()-start)/2,at:performance.now()};setNow(clock.current.server);setData(j);setError('');}catch(e){if(alive)setError((e as Error).message||'No pudimos conectar. Vuelve a intentarlo.');}}refresh.current=load;void load();const interval=setInterval(load,20000);const tick=setInterval(()=>{if(clock.current.server)setNow(clock.current.server+performance.now()-clock.current.at);},250);const focus=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',focus);return()=>{alive=false;clearInterval(interval);clearInterval(tick);document.removeEventListener('visibilitychange',focus);};},[preview]);
 const settings=data?.settings||defaults;const ready=!!data&&(preview||data.unlocked);const digits=remaining(settings.birthday_date,now||Date.parse(settings.birthday_date));
 useEffect(()=>{if(data&&!data.unlocked&&now>=Date.parse(settings.birthday_date)&&!reaching.current){reaching.current=true;void refresh.current().finally(()=>setTimeout(()=>{reaching.current=false;},1000));}},[data,Math.floor(now/1000),settings.birthday_date]);
 function enter(){if(!ready)return;setLeaving(true);setTimeout(()=>{setEntered(true);window.scrollTo(0,0);},650);}
 if(entered&&data)return <Suspense fallback={<div className="loading-page">Abriendo nuestro rincón…</div>}><Album data={data} preview={preview}/></Suspense>;
 return <main className={'welcome '+(leaving?'leaving':'')}><div className="cover-image" style={{backgroundImage:`url("${settings.cover_url}")`}}/><div className="cover-shade"/><div className="grain"/><div className="glints" aria-hidden="true">{Array.from({length:13},(_,i)=><i key={i} style={{left:(7+i*7)%100+'%',top:(i*17)%90+'%',animationDelay:i*.7+'s'}}/>)}</div>
 <header className="welcome-header"><span className="brand"><Heart size={21} strokeWidth={1}/> para mi preciosita</span><span className="date-mark">{limaDate(settings.birthday_date)}</span></header>
 <section className="welcome-content"><p className="eyebrow">UN PEQUEÑO REGALO, CON TODO MI AMOR</p><h1>{ready?<>Llegó <em>tu día.</em><span className="tiny-heart">♡</span></>:<>Algo bonito<br/>te espera <em>aquí.</em></>}</h1><p className="intro">{settings.intro}</p><div className="gold-line"/>
 {ready?<div className="arrival"><p className="main-message">{settings.main_message}</p><button className="primary light" onClick={enter}>Entrar a nuestro rincón <Heart size={16}/><ArrowRight size={17}/></button>{preview&&<p className="preview-note">Vista previa privada · la sorpresa pública sigue su fecha</p>}</div>:<div className="countdown-block"><p>Cada segundo falta un poquito menos<br className="mobile-break"/> para celebrar a mi persona favorita.</p><div className="countdown" role="timer" aria-label="Tiempo que falta para el cumpleaños">{digits.map((d,i)=><div key={i}><span>{data?String(d).padStart(2,'0'):'—'}</span><small>{['DÍAS','HORAS','MINUTOS','SEGUNDOS'][i]}</small></div>)}</div><p className="timezone">{limaDate(settings.birthday_date)} <span>·</span> Hora de Lima, Perú</p><p className="main-message waiting-message">{settings.main_message}</p></div>}
 {error&&<div className="connection-error" role="alert">{error}<button onClick={()=>void refresh.current()}>Volver a intentar</button></div>}</section>
 <footer className="welcome-footer"><span>Hecho de recuerdos. Lleno de ti.</span><Heart className="heartbeat" size={18} strokeWidth={1}/><span>Con amor, siempre.</span></footer></main>;
}
