import {z} from 'zod';
import {authorize,db,getSettings,responseHeaders,removeUnreferenced} from '@/lib/server';
import {defaults,defaultReasons} from '@/lib/content';
export const dynamic='force-dynamic';
const safeUrl=z.string().max(2048).refine(v=>!v||/^\/api\/media\/[a-f0-9-]{36}$/.test(v)||v==='/romantic-rose-letter.webp'||(()=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}})(),'Usa una URL HTTPS directa al archivo.');
const date=z.string().refine(v=>!v||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))),'Fecha inválida.');
const memory=z.object({id:z.string().min(1).max(80),type:z.enum(['photo','video','gif','text']),media_url:safeUrl,thumbnail_url:safeUrl,title:z.string().max(180),description:z.string().max(4000),date,sort_order:z.number().int().min(0).max(10000),visible:z.union([z.literal(0),z.literal(1)]),style:z.enum(['paper','wine']),size:z.enum(['small','medium','large'])}).refine(m=>m.type==='text'?!!(m.title.trim()||m.description.trim()):!!m.media_url,'Agrega un archivo o una frase.');
const moment=z.object({id:z.string().min(1).max(80),date,title:z.string().min(1).max(180),description:z.string().max(4000),media_url:safeUrl,sort_order:z.number().int().min(0).max(10000)});
const reason=z.object({id:z.string().min(1).max(80),text:z.string().min(1).max(300),sort_order:z.number().int().min(0).max(10000)});
const setting=z.object({birthday_date:z.string().refine(v=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}-05:00$/.test(v)&&!isNaN(Date.parse(v)),'La fecha debe usar la hora de Lima (UTC−05:00).'),main_message:z.string().min(1).max(300),intro:z.string().max(1000),letter_content:z.string().max(50000),audio_url:safeUrl,cover_url:safeUrl,timeline_enabled:z.boolean()}).partial().strict();
const names={memories:'memories',timeline:'timeline',reasons:'love_reasons'} as const;
async function initialize(){const existing=await db().prepare('SELECT id FROM settings WHERE id=1').first();if(!existing)await db().batch([db().prepare('INSERT OR IGNORE INTO settings (id,value) VALUES (1,?)').bind(JSON.stringify(defaults)),...defaultReasons.map(r=>db().prepare('INSERT OR IGNORE INTO love_reasons (id,text,sort_order) VALUES (?,?,?)').bind(r.id,r.text,r.sort_order))]);}
export async function POST(req:Request){try{
 const denied=await authorize(req);if(denied)return denied;
 if(Number(req.headers.get('content-length')||0)>200000)return Response.json({error:'El texto es demasiado largo.'},{status:413});
 const body=await req.text();if(body.length>200000)return Response.json({error:'El texto es demasiado largo.'},{status:413});
 const input=z.object({action:z.enum(['save','delete','reorder']),entity:z.enum(['memories','timeline','reasons','settings']),data:z.unknown().optional(),id:z.string().max(80).optional(),ids:z.array(z.string().max(80)).max(500).optional()}).parse(JSON.parse(body));
 await initialize();
 if(input.entity==='settings'){if(input.action!=='save')throw new Error('Acción inválida.');const update=setting.parse(input.data);await db().prepare('UPDATE settings SET value=? WHERE id=1').bind(JSON.stringify({...await getSettings(),...update})).run();}
 else {const table=names[input.entity];if(input.action==='delete'){if(!input.id)throw new Error('Falta el elemento.');const old=await db().prepare(`SELECT * FROM ${table} WHERE id=?`).bind(input.id).first<{media_url?:string;thumbnail_url?:string}>();await db().prepare(`DELETE FROM ${table} WHERE id=?`).bind(input.id).run();if(old)await removeUnreferenced([old.media_url||'',old.thumbnail_url||'']);}
 else if(input.action==='reorder'){const ids=input.ids||[];const rows=await db().prepare(`SELECT id FROM ${table}`).all<{id:string}>();if(ids.length!==rows.results.length||new Set(ids).size!==ids.length||rows.results.some(r=>!ids.includes(r.id)))throw new Error('El álbum cambió. Actualiza el panel y vuelve a ordenar.');if(ids.length)await db().batch(ids.map((id,i)=>db().prepare(`UPDATE ${table} SET sort_order=? WHERE id=?`).bind(i,id)));}
 else if(input.entity==='memories'){const m=memory.parse(input.data);await db().prepare('INSERT INTO memories (id,type,media_url,thumbnail_url,title,description,date,sort_order,visible,style,size,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,media_url=excluded.media_url,thumbnail_url=excluded.thumbnail_url,title=excluded.title,description=excluded.description,date=excluded.date,sort_order=excluded.sort_order,visible=excluded.visible,style=excluded.style,size=excluded.size').bind(m.id,m.type,m.media_url,m.thumbnail_url,m.title,m.description,m.date,m.sort_order,m.visible,m.style,m.size,new Date().toISOString()).run();}
 else if(input.entity==='timeline'){const m=moment.parse(input.data);await db().prepare('INSERT INTO timeline (id,date,title,description,media_url,sort_order) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET date=excluded.date,title=excluded.title,description=excluded.description,media_url=excluded.media_url,sort_order=excluded.sort_order').bind(m.id,m.date,m.title,m.description,m.media_url,m.sort_order).run();}
 else {const r=reason.parse(input.data);await db().prepare('INSERT INTO love_reasons (id,text,sort_order) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET text=excluded.text,sort_order=excluded.sort_order').bind(r.id,r.text,r.sort_order).run();}}
 return Response.json({ok:true},{headers:responseHeaders});
 }catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0].message},{status:400});if(e instanceof SyntaxError)return Response.json({error:'Contenido inválido.'},{status:400});console.error('Admin save failed',e);return Response.json({error:'No se guardaron los cambios. Revisa los campos e inténtalo de nuevo.'},{status:500});}}
